name: markdown-lint

on:
  pull_request:
    branches: [master]
    paths:
      - '**.md'

jobs:
  lint:
    name: "markdown lint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nosborn/github-action-markdown-cli@v3
        with:
          files: .
          config_file: .markdownlint.yaml
